package ru.pearx.carbide

const val CHARATERS_ENGLISH = "abcdefghijklmnopqrstuvwxyz"
const val CHARATERS_ENGLISH_UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const val CHARATERS_DIGITS = "0123456789"
const val CHARATERS_SYMBOLS = """!@#$%^&*()_+"№;:?()=-.,/\|'"""
const val CHARATERS_ENGLISH_ALL = CHARATERS_ENGLISH + CHARATERS_ENGLISH_UPPER
const val CHARATERS_ENGLISH_ALL_DIGITS = CHARATERS_ENGLISH_ALL + CHARATERS_DIGITS
const val CHARATERS_ENGLISH_ALL_DIGITS_SYMBOLS = CHARATERS_ENGLISH_ALL_DIGITS + CHARATERS_SYMBOLS